# Config related to gameplay.
game:
  # Config related to world generation.
  world:
    # The seed to use for world generation. This cannot contain letters. Leave blank to use a random seed.
    seed:
    # Config related to overworld world generation.
    overworld:
      # The world type to use. Accepted values: NORMAL, LARGE_BIOMES, AMPLIFIED, FLAT
      type: NORMAL
    # Whether to generate the nether.
    # If set to false, the plugin will also disable them in server.properties.
    nether: true
    # Whether to generate the end.
    # If set to false, the plugin will also disable them in bukkit.yml.
    # Note that most games will never reach this point.
    end: true
  # Config related to swapping.
  swap:
    # How long to show the started game timer for. Unit is seconds.
    starttimer: 15
    # How long between each swap.
    swaptimer:
      # Minimum amount of time per swap. Unit is seconds.
      min: 120
      # Maximum amount of time per swap. Unit is seconds.
      max: 240
    # How long do players have to prepare when a swap is announced. Unit is seconds.
    time: 10
    # Inform players about a forced swap (done with /swap during an active game)
    informforceswap: true
  # Config related to reconnection of a player.
  reconnect:
    # How long a player has to reconnect to the server if they leave. Unit is seconds.
    grace: 60
  # Config related to post-game
  post:
    # How long before restarting the server after the game end. Unit is seconds.
    restart: 30
# Config for certain actions the plugin will do on your server.
# This is spooky by nature, you can choose to disable it.
server:
  # Attempts to set up restarting automatically if it wasn't.
  setuprestart:
    # Enable this section?
    enable: false
    # The name of your server jar. Leave blank to let the plugin get it, but this might cause errors!
    jarname:
    # The operating system of your server. Leave blank to let the plugin get it.
    # Accepted values: Windows, Mac, Unix, Solaris
    os:
  # Changes some properties in your server for optimization/balancing.
  changeproperties:
    # Whether to disable spawn protection.
    # Set this to true to stop minecraft from blocking placement and destruction of blocks at 0, 0.
    protection: true
    # Whether to disable minecraft's anti cheat.
    # Set this to true to prevent players from being kicked randomly for flying.
    # Consider getting an anticheat plugin.
    anticheat: true
